rokwire/groups-building-block

CHANGELOG.md
core/services.go

Authman sync task should add default admins only to the new groups #198

---

.secrets.baseline
CHANGELOG.md
driver/web/adapter.go
driver/web/auth.go
utils/utils.go

Improve logging of the internal API calls #200

---

CHANGELOG.md
core/application.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/adapter.go
driver/web/rest/adminapis.go
driver/web/rest/internal.go

Introduce admin Authman sync api (POST /admin/authman/synchronize) #202

---

CHANGELOG.md
core/interfaces.go
core/model/group.go
core/model/member.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/apis.go

Improve report a group post as an abuse #204

---

CHANGELOG.md
core/model/config.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
main.go

[#218] Authman groups members missing

---

CHANGELOG.md
core/interfaces.go
core/model/config.go
core/model/group.go
core/model/member.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driven/storage/adapter_v3.go
driven/storage/collection.go
driven/storage/database.go
driver/web/rest/apis.go

[#222] Maximum Mongo document size limit for groups

---

CHANGELOG.md
core/administration.go
core/interfaces.go
core/services.go
driven/storage/adapter.go

[#232] Fix wrong groups pagination

---

CHANGELOG.md
core/interfaces.go
core/model/core.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driver/web/adapter.go
driver/web/rest/apis.go
driver/web/rest/internal.go

[#236] Expose DELETE /api/int/group/{group-id}/events/{event-id} API for using by Events Manager

---

CHANGELOG.md
driven/storage/adapter.go
go.mod

[#250] Exception on get group posts

---

CHANGELOG.md
core/administration.go
core/interfaces.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driver/web/rest/adminapis-v2.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go
driver/web/rest/apis_v2.go

[#253] Implement additional flag for including hidden groups while searching for group name

---

CHANGELOG.md
core/model/member.go
driven/storage/adapter.go

[ID-259]Fix Get Group Members

---

CHANGELOG.md
core/model/member.go
driven/storage/adapter.go

Change showing the ******** and go back to returning the empty string for externalID and name.
resolved #261

[ID-261]Fix Group Members

---

CHANGELOG.md
core/model/user.go
driver/web/auth.go
driver/web/rest/apis.go

[#263] Allow editing of a managed group only if managed_group_admin permission presents for the user 

---

CHANGELOG.md
core/model/event.go
core/model/group_membership.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter_v3.go
driver/web/rest/apis.go

[#270] Override update notifications preferences

---

CHANGELOG.md
core/administration.go
core/interfaces.go
core/model/filters.go
core/model/group.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driven/storage/adapter_v3.go
driven/storage/collection.go
driven/storage/database.go
driver/web/adapter.go
driver/web/rest/adminapis-v2.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go
driver/web/rest/apis_v2.go

[#276] Introduce research groups

---

CHANGELOG.md
driver/web/adapter.go

Expose GET /group/{id}/stats for anonymous tokens 
**Resolves #282**
[comment]: # (To select an option, please put an 'x' …

[#282] Expose GET /group/{id}/stats for anonymous tokens 

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/apis.go

[#285] Wrong property name usage for membership notification preferences for create/update membership records 

---

.secrets.baseline
CHANGELOG.md
Dockerfile
driver/web/adapter.go
driver/web/auth.go
driver/web/permissions_authorization_policy.csv
go.mod
main.go

[#290] Upgrade auth library

---

.secrets.baseline
CHANGELOG.md
README.md
core/interfaces.go
core/model/user.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/corebb/adapter.go
driver/web/adapter.go
driver/web/auth.go
driver/web/permissions_authorization_policy.csv
driver/web/rest/apis.go
go.mod
main.go

[#291] Add API to get count of users matching research profile

---

CHANGELOG.md
core/model/filters.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driven/storage/database.go
go.mod

[#295] Add ability to exclude user's groups from response 

---

CHANGELOG.md
driven/storage/adapter.go

[#301] Disable auto join feature for research groups

---

CHANGELOG.md
core/interfaces.go
driver/web/rest/apis.go

[#305] Fix inappropriate permission check in GET /api/group/{groupId}/posts/{postId} request

---

CHANGELOG.md
core/model/group.go
core/model/group_membership.go
core/model/group_settings.go
core/services.go
driven/storage/adapter.go
driven/storage/database.go
driver/web/rest/apis.go

[#311] Fix backward compatibility for old clients which don't support group settings

---

CHANGELOG.md
driven/storage/adapter.go
driven/storage/adapter_v3.go

[ #313] Change the group sorting only to title

---

CHANGELOG.md
driver/web/rest/apis.go

[#315] Admin must make posts and reactions no matter of group settings 

---

CHANGELOG.md
driven/storage/adapter.go

[#321] Delete group post request fails 

---

CHANGELOG.md
driven/storage/adapter.go
driver/web/rest/apis.go

[#326] Group admins must not see direct messages if they are not listed explicitly within. the ACL list

---

CHANGELOG.md
core/services.go

[#328] Report of offensive speech automatic title 

---

CHANGELOG.md
Makefile
core/interfaces.go
core/model/group.go
core/services.go
driven/storage/adapter.go
driven/storage/adapter_v3.go

[#330] Split date modified field and introduce member & managed member modified date fields

---

CHANGELOG.md
core/interfaces.go
core/model/filters.go
core/model/group.go
core/services_v3.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driven/storage/adapter_v3.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go
driver/web/rest/internal.go

[344] Implement content filters

---

CHANGELOG.md
Dockerfile
Makefile
core/services.go
driven/storage/adapter.go
driven/storage/adapter_v3.go
driven/storage/database.go

[319] Integrate govulncheck

---

CHANGELOG.md
Makefile
core/model/filters.go
core/model/group.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driven/storage/adapter_v3.go
driver/web/rest/apis.go

[348] Rename group filters to attributes

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/apis.go

[#352] Remove category validation on create & update group operations 

---

CHANGELOG.md
driven/storage/adapter.go
driven/storage/collection.go
driven/storage/database.go

[#351] Add indexes for the nested attributes 

---

CHANGELOG.md
core/model/group.go
driven/storage/adapter.go
driven/storage/database.go

This PR addresses the missing backward compatibility, because the new client dropped the support of category & tags as root fields. 
**Resolves #355** …

[#355] Introduce category and tags backward compatibility

---

CHANGELOG.md
core/model/group.go

[#357] Fix cast error within Tags backward compatibility handling

---

CHANGELOG.md
core/interfaces.go
core/services.go
core/services_v3.go
driven/corebb/adapter.go
driven/notifications/adapter.go

Fix sending notifications when creating new group
**Resolves #366

[ID-366]Fix sending notifications when creating new group

---

CHANGELOG.md
driven/storage/database.go

[#374] Fix bad attributes migration for category & tags

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/event.go
core/services.go
core/services_v3.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/calendar/adapter.go
driven/storage/adapter_v3.go
driver/web/adapter.go
driver/web/rest/apis_calendar.go
main.go

[#392] integrate calendar bb

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/services.go
core/services_v3.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/calendar/adapter.go
driver/web/adapter.go
driver/web/rest/apis_calendar.go

[#394] Implement PUT api/group/{id}/events/v3 API for group calendar events

---

CHANGELOG.md
core/model/event.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/calendar/adapter.go

[#396] V3 Load events does not respect time filter

---

CHANGELOG.md
driven/storage/adapter.go
driven/storage/collection.go
driven/storage/database.go

[#399] Fix bad handling of the unique group title index 

---

.secrets.baseline
CHANGELOG.md
core/interfaces.go
core/services.go
driven/authman/adapter.go
driven/calendar/adapter.go
driven/corebb/adapter.go
driven/notifications/adapter.go
driven/rewards/adapter.go
driven/storage/adapter.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go
driver/web/rest/internal.go

[#401] refactor create and update group

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/adminapis-v2.go
driver/web/rest/adminapis.go
driver/web/rest/adminapis_calendar.go
driver/web/rest/apis.go
driver/web/rest/apis_calendar.go
driver/web/rest/apis_v2.go

[#405] Restructure api doc - client & admin grouping 

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/event.go
docs/swagger.json
driven/calendar/adapter.go
driver/web/rest/adminapis_calendar.go
driver/web/rest/apis_calendar.go

Ability to select event admins when creating event linked to multiple groups 
**Resolves #408 
---
[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

[ID-408]Ability to select event admins when creating event linked to multiple groups 

---

CHANGELOG.md
core/application.go
core/model/group_membership.go
core/services.go
core/services_v3.go

[#411] Disable automatic event memership provision for group events

---

CHANGELOG.md
core/application.go
core/interfaces.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/calendar/adapter.go
driver/web/adapter.go
driver/web/rest/adminapis_calendar.go
driver/web/rest/apis_calendar.go

[#414] Do not load "unpublished" events in UIUC client

---

CHANGELOG.md
core/application.go

[#423] Group Admin and Event Admin roles should be treated separately

---

CHANGELOG.md
core/interfaces.go
core/services.go
driven/storage/adapter.go
driven/storage/adapter_v3.go

DELETE api/user API does not remove all user activity in groups [#425]

---

CHANGELOG.md
Dockerfile
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/analytics.go

[#429] Improve analytics apis

---

CHANGELOG.md
core/interfaces.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go

[#434] Split posts and direct messages

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/config.go
core/model/filters.go
core/model/post.go
core/services.go
core/services_analytics.go
core/services_authman.go
core/services_events.go
core/services_scheduled_posts.go
core/services_v3.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/notifications/adapter.go
driven/storage/adapter.go
driven/storage/database.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go

[#437] Schedule post in the future

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/event.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/calendar/adapter.go
driver/web/rest/adminapis_calendar.go
driver/web/rest/apis_calendar.go

[#450] Improve group events APIs

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/member.go
core/model/user.go
core/services.go
driven/storage/adapter.go
driven/storage/adapter_v3.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go

[#452] Improve create group admin api 

---

CHANGELOG.md
core/model/user.go
core/services_authman.go

[#460] Fix missing member name and email for a managed group auto sync task

---

CHANGELOG.md
driver/web/permissions_authorization_policy.csv

[#465] Add new permissions for managing group events independently for granтing access

---

CHANGELOG.md
Dockerfile
driven/storage/adapter.go
driver/web/permissions_authorization_policy.csv
go.mod

[#465] add new role for managing group events

---

CHANGELOG.md
core/interfaces.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/notifications/adapter.go
driver/web/adapter.go
driver/web/rest/apis.go

 [#456] Create Group Report Abuse API 

---

CHANGELOG.md
core/interfaces.go
core/model/post.go
core/services.go
core/services_authman.go
driven/storage/adapter.go

[#468] provide nested replies single post api

---

CHANGELOG.md
core/services.go

Update direct messages notification pattern [#475]

---

CHANGELOG.md
core/admin_membership.go
core/application.go
core/interfaces.go
core/model/filters.go
core/model/group_membership.go
core/model/user.go
core/services.go
core/services_authman.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/corebb/adapter.go
driven/storage/adapter_v3.go
driver/web/adapter.go
driver/web/rest/adminapis.go
driver/web/rest/apis_calendar.go

[#458] Admin API for adding group members by NetIDs #458

---

CHANGELOG.md
core/interfaces.go
core/model/group_membership.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/internal.go

[#477] Do not send polls and direct message notifications as muted when they are not 

---

CHANGELOG.md
core/services.go
core/services_scheduled_posts.go

[#457] Additional fix: Truncate the post body to 250 characters within the notification

---

CHANGELOG.md
driver/web/permissions_authorization_policy.csv

[#481] Use "get_groups" permission for loading user groups in the admin API 

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/adapter.go
driver/web/rest/adminapis.go

POST request for loading group members
**Resolves #455

[ID-455]POST request for loading group members

---

CHANGELOG.md
core/admin_membership.go

Fix Groups Stats are not updated
**Resolves #490 , #483

[ID-490]Fix Groups Stats are not updated

---

CHANGELOG.md
core/admin_membership.go
core/interfaces.go
core/model/operations.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter_v3.go
driver/web/adapter.go
driver/web/rest/apis.go

[#484] Approve all api

---

CHANGELOG.md
SECURITY.md
core/admin_membership.go
core/interfaces.go
core/model/operations.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter_v3.go
driver/web/adapter.go
driver/web/rest/apis.go

merge develop into main

---

CHANGELOG.md
core/interfaces.go
core/model/group.go
core/services_events.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter_events.go
driven/storage/database.go
driver/web/adapter.go
driver/web/authorization_bbs_permission_policy.csv
driver/web/rest/bbapis.go

BBs Api for getting group memberships
**Resolves #494

[ID-494]BBs Api for getting group memberships

---

CHANGELOG.md
core/model/group.go
driven/storage/adapter_events.go

* set the Changelog.md
* fix the aggregation pipeline
---------
[comment]: # (To …

[ID-497] (#498)

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/event.go
core/services_events.go
driven/calendar/adapter.go
driven/storage/adapter_events.go
driver/web/adapter.go
driver/web/authorization_bbs_permission_policy.csv
driver/web/rest/bbapis.go

Calendar events issues
**Resolves #503

[ID-503]Calendar events issues

---

CHANGELOG.md
core/model/user.go

[#509] Bad Authman sync for user who has alternative auth method for first login 

---

CHANGELOG.md
core/interfaces.go
core/services_membership.go
driven/corebb/adapter.go

FERPA issues for group memberships
**Resolves #513

[ID-513] FERPA issues for group memberships

---

CHANGELOG.md
core/interfaces.go
core/services_events.go
docs/swagger.yaml
driven/storage/adapter_events.go
driver/web/adapter.go
driver/web/authorization_bbs_permission_policy.csv
driver/web/rest/bbapis.go

Get groups membership by groupID BBs
**Resolves #516

[ID-517]Get groups membership by groupID BBs

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/corebb/adapter.go
driver/web/adapter.go
driver/web/rest/adminapis-v2.go
driver/web/rest/adminapis.go
driver/web/rest/adminapis_posts.go
driver/web/rest/apis.go
driver/web/rest/apis_calendar.go
driver/web/rest/apis_v2.go
driver/web/rest/bbapis.go

This PR adds a `POST /group/{group-id}/members/v2` API for web clients and it updates the swagger docs to show existing POST APIs for web clients.
**Resolves #524**
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to …

[#524] Implement GET /v2/groups API via http POST method

---

CHANGELOG.md
core/interfaces.go
core/model/user.go
core/services_events.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter_events.go
driver/web/adapter.go
driver/web/rest/apis.go
driver/web/rest/bbapis.go

Consolidate the information, and make it accessible with a single API call
**Resolves #519

[ID-519]Consolidate the information, and make it accessible with a single API call

---

CHANGELOG.md
driver/web/authorization_bbs_permission_policy.csv

[ID-531] Fix migration data permission

---

CHANGELOG.md
core/application.go
core/interfaces.go
core/model/config.go
core/services_posts_migration.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driver/web/adapter.go
driver/web/authorization_bbs_permission_policy.csv
driver/web/rest/bbs_apis.go

[#529] Create posts migrator flag

---

CHANGELOG.md
core/model/user.go
core/services_events.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml

Fix consolidate the information, and make it accessible with a single API call 
**Resolves #538

[ID-538]Fix consolidate the information, and make it accessible with a single API call 

---

core/application.go
core/interfaces.go
core/model/config.go
core/services.go
core/services_posts_migration.go
driven/corebb/adapter.go
driven/socialbb/adapter.go
driven/storage/adapter_events.go
driver/web/rest/bbs_apis.go
main.go

[#537] social bb proxy api call

---

CHANGELOG.md
README.md
core/admin_membership.go
core/interfaces.go
core/services.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/adapter.go
driver/web/rest/admin_apis.go
driver/web/rest/apis.go

[#541] client admin duplicate apis

---

CHANGELOG.md
driven/corebb/adapter.go

[#542] Members fail to load for some groups on prod

---

CHANGELOG.md
core/model/group_settings.go

[#545] Customization options to choose group modules: Polls, Direct Messaging, Posts, Events

---

CHANGELOG.md
core/interfaces.go
core/model/user.go
core/services.go
driven/storage/adapter.go
driver/web/permissions_authorization_policy.csv
driver/web/rest/admin_apis.go
driver/web/rest/admin_apis_v2.go

[#536] feature load all groups

---

CHANGELOG.md
Dockerfile

[ID-558] Support Google Trust Services as CA

---

CHANGELOG.md
core/model/stats_operation.go
driven/storage/adapter.go
driver/web/rest/bbs_apis.go

[#569] Rename param name to post_update in UpdateGroupDateUpdated api

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driver/web/rest/bbs_apis.go

[#572] Fix documentation issue

---

core/model/filters.go
core/model/group.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
driven/storage/adapter.go
driver/web/rest/admin_apis.go
driver/web/rest/apis.go

Here, we need to introduce a new group type - "administrative", and users should be able to create their own administrative groups. In any case, we will introduce a new type: administrative. Users should be able to retrieve only such groups via the API.
**Resolves #576

[ID-576]Add new group type - "administrative" bool

---

CHANGELOG.md
CODEOWNERS
core/admin_membership.go
core/services.go
driven/storage/adapter.go

[#566] Additional fix. Don't update group's date_updated field on a membership update event.

---

CHANGELOG.md
driven/storage/adapter.go

[#584] Update groups sort order

---

CHANGELOG.md
main.go

[#595] Broken env auth algorithm

---

CHANGELOG.md
core/services_authman.go
driven/authman/adapter.go

[#598] Fix and improve Authman sync logs

---

CHANGELOG.md
core/model/user.go
core/services.go

[#606] Not able to add a new staff members NetID to be an admin of a group
